package sisa.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Base account for every person in WSIMS (User & Access Management module).
 * userId follows the school's format, e.g. S2600001 / T2600001 / P2600001 / R2600001,
 * generated by IdGeneratorService. The single Principal account is seeded once
 * and can never be deleted (see DataSeeder + business rule in report section 6.2).
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
public class User {

    @Id
    @Column(length = 20)
    private String userId; // e.g. S2600001, T2600001, P2600001, R2600001, PRINCIPAL

    @Column(nullable = false, unique = true, length = 100)
    private String username;

    @Column(nullable = false)
    private String password; // BCrypt-hashed, never store plain text

    @Column(nullable = false)
    private String fullName;

    @Column(nullable = false)
    private String email;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Role role;

    /** Accounts registered by the Registrar stay PENDING until the Principal approves them. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AccountStatus status = AccountStatus.PENDING;

    @Column(nullable = false)
    private boolean deletable = true; // false only for the permanent Principal account

    @Column(nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    private LocalDateTime lastLoginAt;

    /** Convenience check used by Spring Security and by Thymeleaf pages. */
    public boolean isApproved() {
        return status == AccountStatus.APPROVED;
    }
}

